version: '3'
services:
  bitcoind:
    image: ruimarinho/bitcoin-core:latest
    container_name: bitcoind
    command: -regtest=1
      -server=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=bitcoinuser
      -rpcpassword=bitcoinpassword
      -zmqpubrawblock=tcp://0.0.0.0:28332
      -zmqpubrawtx=tcp://0.0.0.0:28333
      -fallbackfee=0.00001
    ports:
      - '18443:18443'
      - '28332:28332'
      - '28333:28333'
    volumes:
      - ./bitcoin-data:/root/.bitcoin
    networks:
      - lightning-test

  lnd-alice:
    image: lightninglabs/lnd:v0.17.0-beta
    container_name: lnd-alice
    depends_on:
      - bitcoind
    entrypoint: ['bash', '-c']
    command:
      - |
        mkdir -p /root/.lnd
        cat > /root/.lnd/lnd.conf << EOL
        [Application Options]
        debuglevel=info
        maxpendingchannels=10
        restlisten=0.0.0.0:8080
        rpclisten=0.0.0.0:10009
        tlsextraip=0.0.0.0
        tlsextradomain=lnd-alice
        alias=alice

        [Bitcoin]
        bitcoin.active=true
        bitcoin.regtest=true
        bitcoin.node=bitcoind

        [Bitcoind]
        bitcoind.rpchost=bitcoind
        bitcoind.rpcuser=bitcoinuser
        bitcoind.rpcpass=bitcoinpassword
        bitcoind.zmqpubrawblock=tcp://bitcoind:28332
        bitcoind.zmqpubrawtx=tcp://bitcoind:28333
        EOL
        lnd
    ports:
      - '10001:10009'
      - '8001:8080'
    volumes:
      - ./lnd-alice-data:/root/.lnd
    networks:
      - lightning-test

  lnd-bob:
    image: lightninglabs/lnd:v0.17.0-beta
    container_name: lnd-bob
    depends_on:
      - bitcoind
    entrypoint: ['bash', '-c']
    command:
      - |
        mkdir -p /root/.lnd
        cat > /root/.lnd/lnd.conf << EOL
        [Application Options]
        debuglevel=info
        maxpendingchannels=10
        restlisten=0.0.0.0:8080
        rpclisten=0.0.0.0:10009
        tlsextraip=0.0.0.0
        tlsextradomain=lnd-bob
        alias=bob

        [Bitcoin]
        bitcoin.active=true
        bitcoin.regtest=true
        bitcoin.node=bitcoind

        [Bitcoind]
        bitcoind.rpchost=bitcoind
        bitcoind.rpcuser=bitcoinuser
        bitcoind.rpcpass=bitcoinpassword
        bitcoind.zmqpubrawblock=tcp://bitcoind:28332
        bitcoind.zmqpubrawtx=tcp://bitcoind:28333
        EOL
        lnd
    ports:
      - '10002:10009'
      - '8002:8080'
    volumes:
      - ./lnd-bob-data:/root/.lnd
    networks:
      - lightning-test

  lnd-carol:
    image: lightninglabs/lnd:v0.17.0-beta
    container_name: lnd-carol
    depends_on:
      - bitcoind
    entrypoint: ['bash', '-c']
    command:
      - |
        mkdir -p /root/.lnd
        cat > /root/.lnd/lnd.conf << EOL
        [Application Options]
        debuglevel=info
        maxpendingchannels=10
        restlisten=0.0.0.0:8080
        rpclisten=0.0.0.0:10009
        tlsextraip=0.0.0.0
        tlsextradomain=lnd-carol
        alias=carol

        [Bitcoin]
        bitcoin.active=true
        bitcoin.regtest=true
        bitcoin.node=bitcoind

        [Bitcoind]
        bitcoind.rpchost=bitcoind
        bitcoind.rpcuser=bitcoinuser
        bitcoind.rpcpass=bitcoinpassword
        bitcoind.zmqpubrawblock=tcp://bitcoind:28332
        bitcoind.zmqpubrawtx=tcp://bitcoind:28333
        EOL
        lnd
    ports:
      - '10003:10009'
      - '8003:8080'
    volumes:
      - ./lnd-carol-data:/root/.lnd
    networks:
      - lightning-test

  lnd-dave:
    image: lightninglabs/lnd:v0.17.0-beta
    container_name: lnd-dave
    depends_on:
      - bitcoind
    entrypoint: ['bash', '-c']
    command:
      - |
        mkdir -p /root/.lnd
        cat > /root/.lnd/lnd.conf << EOL
        [Application Options]
        debuglevel=info
        maxpendingchannels=10
        restlisten=0.0.0.0:8080
        rpclisten=0.0.0.0:10009
        tlsextraip=0.0.0.0
        tlsextradomain=lnd-dave
        alias=dave

        [Bitcoin]
        bitcoin.active=true
        bitcoin.regtest=true
        bitcoin.node=bitcoind

        [Bitcoind]
        bitcoind.rpchost=bitcoind
        bitcoind.rpcuser=bitcoinuser
        bitcoind.rpcpass=bitcoinpassword
        bitcoind.zmqpubrawblock=tcp://bitcoind:28332
        bitcoind.zmqpubrawtx=tcp://bitcoind:28333
        EOL
        lnd
    ports:
      - '10004:10009'
      - '8004:8080'
    volumes:
      - ./lnd-dave-data:/root/.lnd
    networks:
      - lightning-test

  lnd-eve:
    image: lightninglabs/lnd:v0.17.0-beta
    container_name: lnd-eve
    depends_on:
      - bitcoind
    entrypoint: ['bash', '-c']
    command:
      - |
        mkdir -p /root/.lnd
        cat > /root/.lnd/lnd.conf << EOL
        [Application Options]
        debuglevel=info
        maxpendingchannels=10
        restlisten=0.0.0.0:8080
        rpclisten=0.0.0.0:10009
        tlsextraip=0.0.0.0
        tlsextradomain=lnd-eve
        alias=eve

        [Bitcoin]
        bitcoin.active=true
        bitcoin.regtest=true
        bitcoin.node=bitcoind

        [Bitcoind]
        bitcoind.rpchost=bitcoind
        bitcoind.rpcuser=bitcoinuser
        bitcoind.rpcpass=bitcoinpassword
        bitcoind.zmqpubrawblock=tcp://bitcoind:28332
        bitcoind.zmqpubrawtx=tcp://bitcoind:28333
        EOL
        lnd
    ports:
      - '10005:10009'
      - '8005:8080'
    volumes:
      - ./lnd-eve-data:/root/.lnd
    networks:
      - lightning-test

networks:
  lightning-test:
    driver: bridge
